### ISSUE TITLE
`unpackaged/org-return-dwim` Not Working as Expected

### ISSUE THREAD

**Issue by treitmaier** [alphapapa/unpackaged.el#29]
#### Description
The `unpackaged/org-return-dwim` function is no longer working as expected. When creating a bullet list, pressing return at the end of a line with a list item,  a new item is not created.

#### Steps to Reproduce
1. Create a bullet list in an Org mode document.
2. Press return at the end of a line with a list item.

#### Expected Behavior
A new bullet list item should be created on a new line:
```
- Item1
- $Cursor
```
#### Actual Behavior
A blank line with no new bullet list item is created.
```
- Item1
$Cursor
```
#### Version Information
Doom version: 3.0.0-pre (latest as of 2024-11-01)
Unpackaged: latest as of 2024-11-01
Org version: 9.7.11

#### Additional Information
I have confirmed that `org-return-dwim` is correctly bound and being called, as shown in the `view-lossage` log:
```
 -            ;; org-self-insert-command
 SPC          ;; org-self-insert-command
 i            ;; org-self-insert-command
 t            ;; org-self-insert-command
 e            ;; org-self-insert-command
 m            ;; org-self-insert-command
 1            ;; org-self-insert-command
 <return>     ;; unpackaged/org-return-dwim
```

**Comment by alphapapa** [comment]
Hi,

Thanks for the report, but this was an intentional change: https://github.com/alphapapa/unpackaged.el/commit/0c1f447dab29697d4e30806022f28657c1489375  I have found myself wanting to write content like:

```org
- Foo
  Foo foo foo.
- Bar
  Bar bar bar.
```

And having RET on each item automatically make a new item made that awkward.  Now I just press M-RET to make a new list item.

If you prefer the previous behavior, you can revert that commit, or checkout the code at the previous one, etc.
